Betterments to backend structure
Sukellusilmoitus/backend pull request #39
Opened 2022-04-03 18:39 UTC by makeri89

`index.py` tiedoston refaktorointi. Nyt kaikki api-endpointit löytyy`apis` kansiosta omista moduuleistaan omina namespaceina. Myös frontiin joutui tekemään serviceihin pari muutosta, että toimii.

2022-04-04 08:45 UTC, makeri89 commented
`index.py` jakamisen lisäksi tiedostjen sijainteihin pieniä muutoksia ja joitain pylint-ignoreja poistettu.

2022-04-21 08:16 UTC, Skorp7 requested changes
Mä en saa omalla koneella ajettua enää tiedostoja `src/util/email_sender.py`, `src/util/update_mv_targets.py` enkä mitään kansiosta `email_services` koska models ja util importit ei onnistu. Testaatko että saat ne ajettua? 
Muuten näyttää kaikki toimivan ton frontin PR:n kanssa yhteen.

2022-04-24 18:41 UTC, makeri89 commented
Tuo import error `email_services` kansiosta korjaantuu #51 pullarissa. Tässä korjasin ton `update_mv_targets`in toivottavasti. Tota `email_sender.py` tiedostoa ei kai tarvii suorittaa suoraan komentoriviltä, niin se ei haitanne, jos se ei toimi siinä, sen pitäis kyllä toimia kun se ajetaan muualta koodista, kun sillon noi suhteelliset importpolut toimii.

2022-04-24 18:48 UTC, makeri89 commented
Frontissa [tämä](https://github.com/Sukellusilmoitus/frontend/pull/80) pullari täytyy mergetä samalla, että endpointit toimii.

2022-04-24 20:02 UTC, Skorp7 commented
Kaksi pytestiä feilaa enemmän kuin masterissa.
test_api.py ihan tiedoston lopussa
`def test_user_data_returns_updated_token_when_successful(self): ` ja  
`def test_user_data_doesnt_update_without_auth(self):`

Sovellukesn toiminnot toimii käsin testaamalla. Cypress menee myös läpi. Hylkyjen päivitysskripti toimii nyt.
En osaa sanoa noista api-testeistä, miksei ne toimi.

2022-04-25 06:04 UTC, Skorp7 commented on src/tests/test_api.py
> +        response = requests.put(f'{BASE_URL}/users', json={
```suggestion
        response = requests.put(f'{BASE_URL}/users/', json={
```

2022-04-25 06:06 UTC, Skorp7 approved these changes
Näillä muutoksilla korjaantui noi 2 apitestiä, vielä kun lisää ton yhden kauttaviivan.
Eli nyt feilaa vaan noi token-testit, samat kuin masterissa. Mun puolesta nyt voi mergetä, korjaa ne masterin token testit sitten myöhemmin kun ei ne liity tähän PR:ään.

2022-04-25 13:04 UTC, merged